# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: jagadeeswaran@gmail.com
author_name: jaga
has_binder: true
has_settings: true
kind: frontend
labextension_name: myextension
project_short_description: A JupyterLab extension.
python_name: myextension
repository: https://github.com/jagadeeswaran8848/myextension
test: true

